//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DoctorAccount
    {
        public DoctorAccount()
        {
            this.PatBasicInfor = new HashSet<PatBasicInfor>();
        }
    
        public int Id { get; set; }
        public string UserName { get; set; }
        public string PassWord { get; set; }
        public string Hospital { get; set; }
    
        public virtual ICollection<PatBasicInfor> PatBasicInfor { get; set; }
    }
}
