//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LNCDDataModelContainer : DbContext
    {
        public LNCDDataModelContainer()
            : base("name=LNCDDataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DoctorAccount> DoctorAccountSet { get; set; }
        public DbSet<PatBasicInfor> PatBasicInforSet { get; set; }
        public DbSet<PatMMSE> PatMMSESet { get; set; }
        public DbSet<PatMoCA> PatMoCASet { get; set; }
        public DbSet<PatADL> PatADLSet { get; set; }
        public DbSet<PatOtherTest> PatOtherTestSet { get; set; }
        public DbSet<PatDisease> PatDiseaseSet { get; set; }
        public DbSet<VisitRecord> VisitRecordSet { get; set; }
        public DbSet<PatLabExam> PatLabExamSet { get; set; }
        public DbSet<PatRecentDrug> PatRecentDrugSet { get; set; }
        public DbSet<Drug> DrugSet { get; set; }
        public DbSet<PatPhysicalExam> PatPhysicalExamSet { get; set; }
        public DbSet<SimpleADdata> SimpleADdataSet { get; set; }
    }
}
