//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PatOtherTest
    {
        public int Id { get; set; }
        public string Vocabulary1 { get; set; }
        public string Vocabulary2 { get; set; }
        public string Vocabulary3 { get; set; }
        public string Picture1 { get; set; }
        public string Picture2 { get; set; }
        public string ConnectNumber1 { get; set; }
        public string ConnectNumber2 { get; set; }
        public string Vocabulary4 { get; set; }
        public string VocabularyAnalyse1 { get; set; }
        public string Picture3 { get; set; }
        public string VocabularyAnalyse2 { get; set; }
        public string PatCDR { get; set; }
        public string PatGDS { get; set; }
    
        public virtual VisitRecord VisitRecord { get; set; }
    }
}
