//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace LNCDCDSS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleADdata
    {
        public int Id { get; set; }
        public string SAD1 { get; set; }
        public string SAD2 { get; set; }
        public string SAD3 { get; set; }
        public string SAD4 { get; set; }
        public string SAD5 { get; set; }
        public string SAD61 { get; set; }
        public string SAD7 { get; set; }
        public string SAD8 { get; set; }
        public string SAD9 { get; set; }
        public string SAD10 { get; set; }
        public string SAD11 { get; set; }
        public string SAD62 { get; set; }
        public string SAD63 { get; set; }
        public string SAD12 { get; set; }
        public string SAD13 { get; set; }
        public string DocDia { get; set; }
        public string SysDia { get; set; }
    
        public virtual PatBasicInfor PatBasicInfor { get; set; }
        public virtual VisitRecord VisitRecord { get; set; }
    }
}
